# Generated by Django 4.2.6 on 2023-10-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree_menu.menuitem')),
            ],
            options={
                'verbose_name': 'Верхний пункт меню',
                'verbose_name_plural': 'Верхние пункты меню',
            },
            bases=('tree_menu.menuitem',),
        ),
    ]
